version: "3"
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=realTalk
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: